Fix NoMethodError in version detection section
Fixes "undefined method `empty?' for nil:NilClass (NoMethodError)" in version detection, introduced in commit 16e166a9fde21a8d94c9c0158915ce571793deb8.